# 作者信息
author:
  # 作者名
  name: Youngwen
  # 头像
  avatar: https://github.com/wenxb.png
  # 社交链接 支持 github/bilibili/twitter/facebook/mail
  social:
    github: https://github.com/wenxb
    mail: mailto:i@youngwen.com

# 网站配置
site:
  # 网站网址
  url: "http://localhost:10001"
  # 网站标题
  title: 我的博客
  # 网站描述
  description: ""
  # 网站关键词，多个用空格隔开
  keywords: ""
  # 默认主题模式 暗黑dark/亮色light/自动system
  themeMode: system
  # 备案号
  icp: "萌ICP备 12345678号"

# 页面配置
page:
  # 首页相关
  home:
    # 首页顶部的标题
    title: "YW's Blog"
    # 首页顶部的描述
    desc:
      # text：一组文字，api：使用api接口
      type: 'api'
      api: 'https://v1.hitokoto.cn?c=c&encode=json'
      text:
        - "人类的悲欢并不相通，我只是觉得他们吵闹"
  # 工具页面
  tools:
    # 是否启用工具页面
    enable: true
