# 作者信息
author:
  # 作者名
  name: Youngwen
  # 头像 https://xxx.com/xxx.png
  avatar: https://github.com/shadcn.png

# 网站配置
site:
  # 网址 https://myblog.com
  url: "http://localhost:10001"
  # 主标题
  title: xxx
  # 描述
  description:
  # 关键词，用空格隔开
  keywords: ""
  # 主题模式 暗黑dark/亮色light/自动auto
  themeMode: light
  # 备案号
  icp: "萌ICP备 12345678号"

# 页面配置
page:
  # 首页相关
  home:
    # 首页顶部的标题
    title: "YW's Blog"
    # 首页顶部的描述
    desc:
      # text：一组文字/api：使用api接口
      type: 'api'
      api: 'https://v1.hitokoto.cn?c=c&encode=json'
      text:
        - "人类的悲欢并不相通，我只是觉得他们吵闹"
